#!/usr/bin/env python3
"""
SageMaker serve entrypoint for inference container
"""
import subprocess
import sys

if __name__ == "__main__":
    # Start the Flask inference server
    subprocess.call([sys.executable, "/opt/ml/code/controlnet_lora_handler.py"])